apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: {{ include "demo-app.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-configmap-reader
  namespace: {{ include "demo-app.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-configmap-reader-binding
  namespace: {{ include "demo-app.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: {{ include "demo-app.namespace" . }}
roleRef:
  kind: Role
  name: frontend-configmap-reader
  apiGroup: rbac.authorization.k8s.io
